import { DocumentProps, Head, Html, Main, NextScript } from "next/document";
import { useMemo } from "react";

const Document = ({ __NEXT_DATA__ }: DocumentProps) => {

  return (
    <Html>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body className="bg-zinc-800 text-amber-50">
        <Main />
        <NextScript />
      </body>
    </Html>
  )
}

export default Document
